### ISSUE TITLE
Not working in Magento 2.1.1

### ISSUE THREAD

**Issue by vinitchopra12** [Paytm-Payments/Paytm_Magento_v2.x_Kit#1]
I have setup the extension with the new version of Magento 2.1.0 & 2.1.1. The payment option is not appearing in the checkout page. I have upgraded the extension with this repo. 

Please update me asap.

**Comment by manishrtpl** [comment]
Hello Vinit,

Have you resolved that issue, please share.

**Comment by vinitchopra12** [comment]
Yes, the issue has been resolved.

**Comment by manishrtpl** [comment]
Please share where I need to change in code?
